name: OWASP ZAP Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

steps:
  - name: ZAP Scan
    uses: zaproxy/action-full-scan@v0.8.0
    with:
      target: 'https://www.zaproxy.org/'
