name: OWASP ZAP Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: OWASP ZAP Full Scan
        uses: owasp/zap-full-scan@v1
        with:
          target: https://zstone.dev
          report: true
